version: '3'


services:
  redis:
    image: "redislabs/redismod:latest"
    ports:
      - "6379:6379"
  application:
    image: "maguec/adgears:0.4.1"
    links:
      - "redis:redis"
    ports:
      - "5000:5000"
    environment:
        - REDIS_SERVER=redis
        - REDIS_PORT=6379
